import type { BucketItem, ChatMessage, Persona, PlanningCriteria, Recommendation, ZymixMessage } from "@/lib/domain";

export const personas: Persona[] = [
  {
    id: "jeff",
    name: "Jeff",
    color: "#0f766e",
    postalCode: "E1 6AN",
    defaultBudgetMax: 35
  },
  {
    id: "praya",
    name: "Praya",
    color: "#b04473",
    postalCode: "SW9 8JH",
    defaultBudgetMax: 28
  },
  {
    id: "tana",
    name: "Tana",
    color: "#5a7f36",
    postalCode: "N1C 4QP",
    defaultBudgetMax: 32
  },
  {
    id: "tester",
    name: "Tester",
    color: "#2457c5",
    postalCode: "SE10 9NF",
    defaultBudgetMax: 20
  }
];

export const seededBucketItems: BucketItem[] = [
  {
    id: "pipeline-7501063875228339487-01-layla",
    userId: "jeff",
    status: "saved",
    dateType: "anytime",
    title: "Layla Bakery",
    category: "cafe",
    description: "Portobello Road bakery known for sourdough, pastries and coffee in the Notting Hill and Ladbroke Grove area.",
    whyInteresting: "Seeded from the London bakery TikTok cleanup as a polished replacement for the Paris batch.",
    locationName: "Layla",
    neighborhood: "Notting Hill / Ladbroke Grove",
    address: "332 Portobello Road, London, UK",
    postalCode: "W10 5PQ",
    priceEstimate: "$$",
    estimatedCost: 18,
    openingHours:
      "Not clearly published; typical independent bakery hours are morning to mid-afternoon, but check latest before visiting.",
    websiteUrl: "https://laylabakery.com/",
    sourceUrl: "https://vm.tiktok.com/ZNRvUw3uT/",
    sourceType: "tiktok",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://laylabakery.com/", "https://vm.tiktok.com/ZNRvUw3uT/"],
    enrichmentConfidenceNote: "Official hours were not clearly published online; verify before visiting.",
    tags: ["bakery", "coffee", "sourdough", "pastries", "artisan"],
    confidence: 0.82,
    createdAt: "2026-06-07T12:00:00Z",
    updatedAt: "2026-06-07T12:00:00Z"
  },
  {
    id: "pipeline-7501063875228339487-02-kuro-bakery",
    userId: "jeff",
    status: "saved",
    dateType: "anytime",
    title: "KURO Bakery",
    category: "cafe",
    description: "Notting Hill bakery from the KURO group, focused on sourdough, pastries, coffee and takeaway bakery runs.",
    whyInteresting: "A strong Notting Hill bakery pick from the London TikTok batch with clear official details.",
    locationName: "KURO Bakery",
    neighborhood: "Notting Hill",
    address: "95 Notting Hill Gate, London W11 3JZ",
    postalCode: "W11 3JZ",
    priceEstimate: "$$",
    estimatedCost: 18,
    openingHours: "Mon-Fri 08:00-16:00; Sat-Sun 08:00-17:00",
    websiteUrl: "https://kuro-london.com/kuro-bakery-london",
    sourceUrl: "https://vm.tiktok.com/ZNRvUw3uT/",
    sourceType: "tiktok",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://kuro-london.com/kuro-bakery-london", "https://vm.tiktok.com/ZNRvUw3uT/"],
    tags: ["bakery", "notting-hill", "sourdough", "pastries", "takeaway"],
    confidence: 0.88,
    createdAt: "2026-06-07T12:01:00Z",
    updatedAt: "2026-06-07T12:01:00Z"
  },
  {
    id: "pipeline-7501063875228339487-03-jolene",
    userId: "jeff",
    status: "saved",
    dateType: "anytime",
    title: "Jolene Redchurch Street",
    category: "cafe",
    description: "Shoreditch bakery and cafe serving coffee, pastries, sourdough and takeaway-friendly bakery items.",
    whyInteresting: "A local Shoreditch bakery option from the London TikTok batch, close to Jeff's usual area.",
    locationName: "Jolene Redchurch Street",
    neighborhood: "Shoreditch",
    address: "67 Redchurch Street, Shoreditch, London E2 7DJ",
    postalCode: "E2 7DJ",
    priceEstimate: "$",
    estimatedCost: 14,
    openingHours: "Mon-Fri 08:00-16:00; Sat-Sun 09:00-16:00",
    websiteUrl: "https://www.jolenebakery.com/location/jolene-redchurch-street",
    sourceUrl: "https://vm.tiktok.com/ZNRvUw3uT/",
    sourceType: "tiktok",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: [
      "https://www.jolenebakery.com/location/jolene-redchurch-street",
      "https://vm.tiktok.com/ZNRvUw3uT/"
    ],
    tags: ["bakery", "coffee", "pastries", "takeaway", "sourdough"],
    confidence: 0.9,
    createdAt: "2026-06-07T12:02:00Z",
    updatedAt: "2026-06-07T12:02:00Z"
  },
  {
    id: "monmouth-coffee",
    userId: "jeff",
    status: "saved",
    dateType: "anytime",
    title: "Monmouth Coffee",
    category: "cafe",
    description: "Beloved independent coffee roaster with a small cosy space in Borough Market.",
    whyInteresting: "Best pour-over in London — perfect before a market wander.",
    locationName: "Monmouth Coffee",
    neighborhood: "Borough Market",
    address: "2 Park St, London SE1 9AB",
    postalCode: "SE1 9AB",
    priceEstimate: "$",
    estimatedCost: 8,
    openingHours: "Open daily",
    openingHoursRows: [
      { day: "Mon – Fri", hours: "7:30 – 18:00" },
      { day: "Saturday",  hours: "9:00 – 17:00" },
      { day: "Sunday",    hours: null },
    ],
    sourceType: "tiktok",
    tags: ["coffee", "cosy", "independent"],
    confidence: 0.89,
    createdAt: "2026-06-06T09:50:00Z",
    updatedAt: "2026-06-06T09:50:00Z"
  },
  {
    id: "brat-live-share",
    userId: "praya",
    status: "saved",
    dateType: "anytime",
    title: "BRAT",
    category: "restaurant",
    description: "Michelin-starred Shoreditch restaurant known for open-fire cooking, whole turbot, seafood and Basque-inspired dishes.",
    whyInteresting: "A viral food pick with a clear special-occasion angle and strong TikTok recognition.",
    locationName: "Brat",
    neighborhood: "Shoreditch",
    address: "First Floor, 4 Redchurch Street",
    postalCode: "E1 6JL",
    priceEstimate: "$$$",
    estimatedCost: 70,
    openingHours: "Mon-Fri 12:00-14:30, 17:30-22:00; Sat-Sun 12:00-15:30, 17:30-22:00",
    websiteUrl: "https://bratrestaurant.co.uk/",
    sourceUrl: "https://bratrestaurant.co.uk/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://bratrestaurant.co.uk/"],
    tags: ["open-fire", "seafood", "basque-inspired", "modern-british", "trendy"],
    confidence: 0.9,
    createdAt: "2026-06-06T12:10:00Z",
    updatedAt: "2026-06-06T12:10:00Z"
  },
  {
    id: "canova-hall",
    userId: "praya",
    status: "saved",
    dateType: "anytime",
    title: "Canova Hall (now The Ferndale)",
    category: "nightlife",
    description: "Brixton drinks and casual food spot now operating as The Ferndale, with cocktails, pizza and group-friendly pub energy.",
    whyInteresting: "Works as a casual south London group option that can bridge food and drinks.",
    locationName: "Canova Hall",
    neighborhood: "Brixton",
    address: "250 Ferndale Road, London",
    postalCode: "SW9 8BQ",
    priceEstimate: "$$",
    estimatedCost: 30,
    openingHours: "Mon-Wed 12:00-00:00; Thu 12:00-00:30; Fri-Sat 12:00-02:00; Sun 12:00-22:30",
    websiteUrl: "https://www.urbanpubsandbars.com/venues/the-ferndale",
    sourceUrl: "https://www.urbanpubsandbars.com/venues/the-ferndale",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.urbanpubsandbars.com/venues/the-ferndale"],
    tags: ["brixton", "cocktails", "pizza", "pub", "group-friendly"],
    confidence: 0.82,
    createdAt: "2026-06-06T11:40:00Z",
    updatedAt: "2026-06-06T11:40:00Z"
  },
  {
    id: "gymkhana-mayfair",
    userId: "praya",
    status: "saved",
    dateType: "anytime",
    title: "Gymkhana",
    category: "restaurant",
    description: "Upscale Mayfair Indian restaurant with Michelin recognition, tasting menus and highly shared signature dishes.",
    whyInteresting: "A high-end viral dinner option when the group wants a more polished plan.",
    locationName: "Gymkhana",
    neighborhood: "Mayfair",
    address: "42 Albemarle Street",
    postalCode: "W1S 4JH",
    priceEstimate: "$$$",
    estimatedCost: 120,
    openingHours: "Daily 12:00-14:45, 17:30-22:45; check current booking slots",
    websiteUrl: "https://gymkhanalondon.com/",
    sourceUrl: "https://gymkhanalondon.com/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://gymkhanalondon.com/"],
    tags: ["indian", "fine-dining", "michelin-starred", "tasting-menu", "mayfair"],
    confidence: 0.93,
    createdAt: "2026-06-06T11:42:00Z",
    updatedAt: "2026-06-06T11:42:00Z"
  },
  {
    id: "padel-social-club",
    userId: "praya",
    status: "saved",
    dateType: "anytime",
    title: "Padel Social Club, Earls Court",
    category: "activity",
    description: "Outdoor padel club in Earls Court with bookable courts, coaching and social activity energy.",
    whyInteresting: "A useful activity-first option when the group wants something more active than dinner.",
    locationName: "Padel Social Club - Earl's Court",
    neighborhood: "Earls Court",
    address: "Empress Place, London SW6 1TT",
    postalCode: "SW6 1TT",
    priceEstimate: "$$",
    estimatedCost: 32,
    openingHours: "Mon-Fri 06:00-23:00; Sat-Sun 07:00-23:00",
    websiteUrl: "https://padelsocial.club/pages/earls-court",
    sourceUrl: "https://padelsocial.club/pages/earls-court",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://padelsocial.club/pages/earls-court"],
    tags: ["padel", "sports", "social", "wellness", "outdoor"],
    confidence: 0.9,
    createdAt: "2026-06-06T11:45:00Z",
    updatedAt: "2026-06-06T11:45:00Z"
  },
  {
    id: "borough-market",
    userId: "praya",
    status: "saved",
    dateType: "anytime",
    title: "Borough Market",
    category: "shopping",
    description: "Historic London Bridge food market with stalls, produce, street food and plenty of flexible group choices.",
    whyInteresting: "Good for mixed preferences because everyone can pick a different stall without locking into one cuisine.",
    locationName: "London Bridge",
    neighborhood: "Southwark",
    address: "8 Southwark Street, London SE1 1TL",
    postalCode: "SE1 1TL",
    priceEstimate: "$$",
    estimatedCost: 25,
    openingHours: "Mon closed; Tue-Fri 10:00-17:00; Sat 09:00-17:00; Sun 10:00-16:00",
    websiteUrl: "https://boroughmarket.org.uk/visit-us/",
    sourceUrl: "https://boroughmarket.org.uk/visit-us/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://boroughmarket.org.uk/visit-us/"],
    tags: ["food-market", "historic", "street-food", "shopping", "london-bridge"],
    confidence: 0.95,
    createdAt: "2026-06-06T11:36:00Z",
    updatedAt: "2026-06-06T11:36:00Z"
  },
  {
    id: "dishoom-kings-cross",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "Dishoom King's Cross",
    category: "restaurant",
    description: "Popular Indian restaurant in King's Cross with all-day dining, reliable group appeal and a queue-famous reputation.",
    whyInteresting: "A crowd-pleasing food option close to Tana's area, with a clear queue-management warning.",
    locationName: "Dishoom King's Cross",
    neighborhood: "King's Cross",
    address: "5 Stable Street",
    postalCode: "N1C 4AB",
    priceEstimate: "$$",
    estimatedCost: 35,
    openingHours: "Mon-Wed 08:00-23:00; Thu-Fri 08:00-00:00; Sat 09:00-00:00; Sun 09:00-23:00",
    openingHoursRows: [
      { day: "Mon – Fri", hours: "8:00 – 23:00" },
      { day: "Sat – Sun", hours: "9:00 – 23:00" },
    ],
    websiteUrl: "https://www.dishoom.com/kings-cross/",
    sourceUrl: "https://www.dishoom.com/kings-cross/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.dishoom.com/kings-cross/"],
    tags: ["indian", "busy", "queue-famous", "all-day-dining", "popular"],
    confidence: 0.96,
    createdAt: "2026-06-06T11:48:00Z",
    updatedAt: "2026-06-06T11:48:00Z"
  },
  {
    id: "fabric",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "fabric",
    category: "nightlife",
    description: "Long-running Farringdon nightclub known for electronic music, late-night programming and big DJ lineups.",
    whyInteresting: "A clear nightlife use case for a group that wants a late, high-energy option.",
    locationName: "fabric",
    neighborhood: "Farringdon",
    address: "77A Charterhouse Street",
    postalCode: "EC1M 6HJ",
    priceEstimate: "$$",
    estimatedCost: 35,
    openingHours: "Fri 23:00-07:00; Sat 23:00-08:00; Sun 23:00-05:30; check event listings",
    websiteUrl: "https://www.fabriclondon.com/",
    sourceUrl: "https://www.fabriclondon.com/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.fabriclondon.com/"],
    tags: ["nightclub", "electronic", "late-night", "dj", "dance"],
    confidence: 0.92,
    createdAt: "2026-06-06T11:30:00Z",
    updatedAt: "2026-06-06T11:30:00Z"
  },
  {
    id: "fold",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "FOLD",
    category: "nightlife",
    description: "Canning Town club and arts space with techno-heavy programming, late hours and a 24-hour licence.",
    whyInteresting: "Adds a more underground nightlife option to contrast with Fabric.",
    locationName: "FOLD",
    neighborhood: "Canning Town",
    address: "Gillian House, Stephenson Street, London E16 4SA",
    postalCode: "E16 4SA",
    priceEstimate: "$$",
    estimatedCost: 28,
    openingHours: "Varies by event; check current listings for door times and schedules",
    websiteUrl: "https://www.fold.london/",
    sourceUrl: "https://www.fold.london/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.fold.london/"],
    tags: ["nightclub", "techno", "late-night", "queer-friendly", "east-london"],
    confidence: 0.9,
    createdAt: "2026-06-06T11:32:00Z",
    updatedAt: "2026-06-06T11:32:00Z"
  },
  {
    id: "tate-modern",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "Tate Modern",
    category: "culture",
    description: "Major modern and contemporary art museum on Bankside with free collection entry and rotating paid exhibitions.",
    whyInteresting: "A low-cost culture fallback with river walk potential before or after.",
    locationName: "Tate Modern",
    neighborhood: "Bankside",
    address: "Bankside, London SE1 9TG, United Kingdom",
    postalCode: "SE1 9TG",
    priceEstimate: "$",
    estimatedCost: 0,
    openingHours: "Sun-Thu 10:00-18:00; Fri-Sat 10:00-21:00; check holiday closures",
    websiteUrl: "https://www.tate.org.uk/visit/tate-modern",
    sourceUrl: "https://www.tate.org.uk/visit/tate-modern",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.tate.org.uk/visit/tate-modern"],
    tags: ["art", "museum", "modern-art", "free-entry", "architecture"],
    confidence: 0.96,
    createdAt: "2026-06-06T11:20:00Z",
    updatedAt: "2026-06-06T11:20:00Z"
  },
  {
    id: "gods-own-junkyard",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "Gods Own Junkyard",
    category: "culture",
    description: "Walthamstow neon gallery and cafe filled with signs, film props and photogenic lighting.",
    whyInteresting: "A hidden-gem culture option with strong visual payoff for a group weekend plan.",
    locationName: "God's Own Junkyard",
    neighborhood: "Walthamstow",
    address: "Unit 12, Ravenswood Industrial Estate, Shernhall Street, London",
    postalCode: "E17 9HQ",
    priceEstimate: "$",
    estimatedCost: 0,
    openingHours: "Fri 11:00-22:00; Sat 11:00-22:00; Sun 11:00-18:00; check ahead for private closures",
    websiteUrl: "https://www.godsownjunkyard.co.uk/",
    sourceUrl: "https://www.godsownjunkyard.co.uk/",
    sourceType: "manual",
    enrichmentProvider: "perplexity",
    enrichmentStatus: "complete",
    enrichmentSourceLinks: ["https://www.godsownjunkyard.co.uk/"],
    tags: ["art", "gallery", "photography", "hidden-gem", "neon"],
    confidence: 0.92,
    createdAt: "2026-06-06T11:25:00Z",
    updatedAt: "2026-06-06T11:25:00Z"
  },
  {
    id: "bread-ahead-bakery",
    userId: "tana",
    status: "saved",
    dateType: "anytime",
    title: "Bread Ahead Bakery",
    category: "cafe",
    description: "Famous Borough Market bakery known for doughnuts and sourdough.",
    whyInteresting: "Iconic London bakery — easy crowd-pleaser for a morning plan.",
    locationName: "Bread Ahead",
    neighborhood: "Borough Market",
    address: "Cathedral St, London SE1 9AL",
    postalCode: "SE1 9AL",
    priceEstimate: "$",
    estimatedCost: 12,
    openingHours: "Open daily",
    sourceType: "instagram",
    tags: ["bakery", "breakfast", "viral"],
    confidence: 0.93,
    createdAt: "2026-06-06T10:00:00Z",
    updatedAt: "2026-06-06T10:00:00Z"
  }
];

export const seededCriteria: PlanningCriteria[] = [
  {
    userId: "jeff",
    budgetMax: 35,
    availableTimes: ["Tonight after 7", "Sunday afternoon"],
    postalCode: "E1 6AN",
    vetoes: ["clubs"]
  },
  {
    userId: "praya",
    budgetMax: 30,
    availableTimes: ["Tonight after 7", "Sunday afternoon"],
    postalCode: "SW9 8JH",
    vetoes: ["too expensive"]
  },
  {
    userId: "tana",
    budgetMax: 25,
    availableTimes: ["Sunday afternoon"],
    postalCode: "N1C 4QP",
    vetoes: ["long queues"]
  },
  {
    userId: "tester",
    budgetMax: 20,
    availableTimes: ["Tonight after 7", "Sunday afternoon"],
    postalCode: "SE10 9NF",
    vetoes: ["over budget"]
  }
];

export const seededRecommendations: Recommendation[] = [
  {
    bucketItemId: "borough-market",
    score: 94,
    reasons: ["Under all budgets", "Flexible food choices avoid vetoes", "Central enough for all three"],
    warnings: ["Best before late afternoon"]
  },
  {
    bucketItemId: "tate-modern",
    score: 88,
    reasons: ["Low-cost option", "Works on Sunday afternoon", "Easy add-on with a river walk"],
    warnings: []
  },
  {
    bucketItemId: "dishoom-kings-cross",
    score: 81,
    reasons: ["Group-friendly food", "Near Tana's postcode", "Reliable fallback with a clear plan"],
    warnings: ["Queue risk; book or arrive early"]
  }
];

export const seededMessages: ChatMessage[] = [
  {
    id: "msg-1",
    userId: "praya",
    text: "We need something for Sunday that doesn't become another 80-message debate.",
    createdAt: "2026-06-06T12:00:00Z"
  },
  {
    id: "msg-2",
    userId: "jeff",
    text: "@planner use our saved spots and find the best 3 options.",
    createdAt: "2026-06-06T12:01:00Z"
  },
  {
    id: "msg-3",
    userId: "planner",
    text: "Got it. I need budget, availability, postcode, and vetoes from Jeff, Praya, and Tana.",
    createdAt: "2026-06-06T12:01:12Z"
  }
];

export const seededZymixMessages: ZymixMessage[] = [
  {
    id: "zymix-seablings-praya-hi",
    threadId: "group:seablings",
    userId: "praya",
    text: "hi",
    createdAt: "2026-06-06T12:09:00Z"
  }
];
